### ISSUE TITLE
Sample Comment Design

### ISSUE THREAD

**Issue by RIR360** [RIR360/FB-Post#36]
Assigned to: @saadman-galib 
# Design 3 sample comments
You have to design the comment only nothing else for now.
## Example:
![image](https://user-images.githubusercontent.com/50569315/120887503-1abae180-c615-11eb-993f-2665e01c04bb.png)
![image](https://user-images.githubusercontent.com/50569315/120887744-75087200-c616-11eb-832c-4ae8935ddfb5.png)

**Comment by saadman-galib** [comment]
Ok bhaiya
